# Generated by Django 6.1 on 2026-09-14 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("works", "0003_work_selected_worker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_RECEIVED", "Application Received"),
                            ("WORKER_SELECTED", "Worker Selected"),
                            ("APPLICATION_REJECTED", "Application Rejected"),
                            ("WORK_SUBMITTED", "Work Submitted"),
                            ("WORK_COMPLETED", "Work Completed"),
                            ("REVIEW_RECEIVED", "Review Received"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="works.work",
                    ),
                ),
            ],
        ),
    ]
